# Generated by Django 2.2.6 on 2020-05-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Bags')),
                ('product_clothing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Clothing')),
                ('product_footwear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Footwear')),
            ],
        ),
    ]
