# Generated by Django 2.2.6 on 2020-05-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_bags',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_clothing',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_footwear',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
    ]
