# Generated by Django 2.2.6 on 2020-06-23 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trsn_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('trsn_id', models.IntegerField(verbose_name='Transaction id')),
                ('order_id', models.IntegerField(verbose_name='Order Id')),
                ('trsn_amount', models.IntegerField(verbose_name='Transaction Amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
