# Generated by Django 2.2.6 on 2020-06-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200623_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='user',
        ),
    ]
