# Generated by Django 2.2.6 on 2020-05-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='product_type',
            field=models.CharField(choices=[('Mens', 'Mens'), ('womens', 'womens'), ('kids', 'kids')], default='shirt', max_length=20),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(choices=[('Mens', 'Mens'), ('womens', 'womens'), ('kids', 'kids')], default='Male', max_length=20),
        ),
    ]
