# Generated by Django 2.2.6 on 2020-05-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200504_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'shirt'), ('t-shirt', 't-shirt'), ('jeans', 'jeans'), ('trousers', 'trousers')], default='shirt', max_length=20),
        ),
    ]
