# Generated by Django 2.2.6 on 2020-05-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200504_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_title', models.CharField(max_length=100)),
                ('item_details', models.TextField(max_length=1000)),
                ('product', models.ImageField(blank=True, upload_to='footwear/%y/%m/%d/')),
                ('size', models.CharField(choices=[('uk-5', 'uk-5'), ('uk-6', 'uk-6'), ('uk-7', 'uk-7'), ('uk-8', 'uk-8'), ('uk-9', 'uk-9'), ('uk-10', 'uk-10'), ('uk-11', 'uk-11')], default='m', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=20)),
                ('category', models.CharField(choices=[('Mens', 'Mens'), ('womens', 'womens'), ('kids', 'kids')], default='Male', max_length=20)),
                ('product_type', models.CharField(choices=[('formal', 'formal'), ('sports', 'sports'), ('casual', 'casual'), ('sandal', 'sandal'), ('sleeper', 'sleeper')], default='shirt', max_length=20)),
                ('price', models.FloatField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
