# Generated by Django 2.2.6 on 2020-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_footwear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_title', models.CharField(max_length=100)),
                ('item_details', models.TextField(max_length=1000)),
                ('product', models.ImageField(blank=True, upload_to='footwear/%y/%m/%d/')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=20)),
                ('category', models.CharField(choices=[('Mens', 'Mens'), ('womens', 'womens'), ('kids', 'kids')], default='Male', max_length=20)),
                ('product_type', models.CharField(choices=[('hand_bag', 'hand_bag'), ('backpack', 'backpack'), ('shoulder_bag', 'shoulder_bag'), ('messenger_bag', 'messenger_bag'), ('hobo_bag', 'hobo_bag'), ('travelling_bag', 'travelling_bag')], default=None, max_length=20)),
                ('price', models.FloatField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='footwear',
            name='product_type',
            field=models.CharField(choices=[('formal', 'formal'), ('sports', 'sports'), ('casual', 'casual'), ('sandal', 'sandal'), ('sleeper', 'sleeper')], default=None, max_length=20),
        ),
    ]
