# Generated by Django 2.2.6 on 2020-05-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200507_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_title', models.CharField(max_length=100)),
                ('item_details', models.TextField(max_length=1000)),
                ('product', models.ImageField(blank=True, upload_to='products/%y/%m/%d/')),
                ('size', models.CharField(choices=[('m', 'M'), ('sm', 'SM'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('uk-5', 'uk-5'), ('uk-6', 'uk-6'), ('uk-7', 'uk-7'), ('uk-8', 'uk-8'), ('uk-9', 'uk-9'), ('uk-10', 'uk-10'), ('uk-11', 'uk-11')], default='m', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=20)),
                ('category', models.CharField(choices=[('Mens', 'Mens'), ('womens', 'womens'), ('kids', 'kids')], default='Male', max_length=20)),
                ('product_type', models.CharField(choices=[('shirt', 'shirt'), ('t-shirt', 't-shirt'), ('jeans', 'jeans'), ('trousers', 'trousers'), ('formal', 'formal'), ('sports', 'sports'), ('casual', 'casual'), ('sandal', 'sandal'), ('sleeper', 'sleeper'), ('hand_bag', 'hand_bag'), ('backpack', 'backpack'), ('shoulder_bag', 'shoulder_bag'), ('messenger_bag', 'messenger_bag'), ('hobo_bag', 'hobo_bag'), ('travelling_bag', 'travelling_bag')], default='shirt', max_length=20)),
                ('price', models.FloatField()),
                ('item_stock', models.FloatField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
