# Generated by Django 2.2.6 on 2020-06-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200526_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'shirt'), ('t-shirt', 't-shirt'), ('jeans', 'jeans'), ('trousers', 'trousers'), ('formal', 'formal'), ('sports', 'sports'), ('casual', 'casual'), ('sandal', 'sandal'), ('sleeper', 'sleeper'), ('hand_bag', 'hand_bag'), ('backpack', 'backpack'), ('shoulder_bag', 'shoulder_bag'), ('messenger_bag', 'messenger_bag'), ('hobo_bag', 'hobo_bag'), ('travelling_bag', 'travelling_bag'), ('digital', 'digital'), ('analog', 'analog'), ('hybrid', 'hybrid'), ('smart_band', 'smart_band')], default='shirt', max_length=20),
        ),
    ]
